Update styles file .css
SUGAM-ARORA/UniCollab pull request #534
Opened 2024-07-23 04:19 UTC by ankitmodanwall

There are a big changes which transform the previous background into animated b-g that enhance the visibility as their record is available below

## Related Issue
:-  background visibility.

## Description
i added a animated background which is nicely visible
## Type of PR

- [yes] Bug fix
- [yes] Feature enhancement
- [yes] Documentation update

## Screenshots / videos (if applicable)

https://github.com/user-attachments/assets/8e25b76d-9409-481a-b75f-c45e4de64424

## Checklist:
- [yes] I have performed a self-review of my code
- [yes] I have read and followed the Contribution Guidelines.
- [yes] I have tested the changes thoroughly before submitting this pull request.
- [yes] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [yes ] I have commented my code, particularly in hard-to-understand areas.

## Additional context:
[Include any additional information or context that might be helpful for reviewers.]

2024-07-23 04:21 UTC, ankitmodanwall commented
Thank you

2024-07-23 07:02 UTC, SUGAM-ARORA requested changes
@ankitmodanwall Kindly share the Issue with which it is aligned d

2024-07-23 07:44 UTC, ankitmodanwall commented
The issue is that background was not animated with RGB colours as privious had..

2024-07-23 19:30 UTC, SUGAM-ARORA commented
> The issue is that background was not animated with RGB colours as privious had..

Issue number needed

2024-07-24 12:58 UTC, ankitmodanwall commented
you should merge it into your file because it is enhancing the background of cover page.

2024-07-24 18:10 UTC, SUGAM-ARORA commented
> #549

@ankitmodanwall Kindly raise a Issue first and check whether this is required or not.

2024-07-25 17:13 UTC, SUGAM-ARORA commented
> see the issue is that your cover page background which is not attractive since you added it so you should see the animated BG then merge it.

Still need to create an issue first . THis is the standard procedure. Kindly please follow

2025-07-25 06:22 UTC, closed without merging